task: detection

model: RTDETR
criterion: RTDETRCriterionv2
postprocessor: RTDETRPostProcessor


use_focal_loss: True
eval_spatial_size: [640, 640] # h w


RTDETR: 
  backbone: PResNet
  encoder: HybridEncoder
  decoder: RTDETRTransformerv2
  

PResNet:
  depth: 50
  variant: d
  freeze_at: 0
  return_idx: [1, 2, 3]
  num_stages: 4
  freeze_norm: True
  pretrained: True 


HybridEncoder:
  in_channels: [512, 1024, 2048]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 256
  use_encoder_idx: [2]
  num_encoder_layers: 1
  nhead: 8
  dim_feedforward: 1024
  dropout: 0.
  enc_act: 'gelu'
  
  # cross
  expansion: 1.0
  depth_mult: 1
  act: 'silu'


RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3

  num_layers: 6
  num_queries: 300

  num_denoising: 100
  label_noise_ratio: 0.5
  box_noise_scale: 1.0 # 1.0 0.4

  eval_idx: -1

  # NEW
  num_points: [4, 4, 4] # [3,3,3] [2,2,2]
  cross_attn_method: default # default, discrete
  query_select_method: default # default, agnostic 


RTDETRPostProcessor:
  num_top_queries: 300


RTDETRCriterionv2:
  weight_dict: {loss_vfl: 1, loss_bbox: 5, loss_giou: 2,}
  losses: ['vfl', 'boxes', ]
  alpha: 0.75
  gamma: 2.0

  matcher:
    type: HungarianMatcher
    weight_dict: {cost_class: 2, cost_bbox: 5, cost_giou: 2}
    alpha: 0.25
    gamma: 2.0




## Optimizer/ lr scheduler params
use_amp: True
use_ema: True 
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 2000


epochs: 72
clip_max_norm: 0.1

optimizer:
  type: AdamW
  params: 
    - 
      params: '^(?=.*backbone)(?!.*norm).*$'
      lr: 0.00001
    - 
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


lr_scheduler:
  type: MultiStepLR
  milestones: [1000]
  gamma: 0.1


lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 2000



# output_dir: ./output/rtdetrv2_r50vd_6x_coco


# dataloader params
train_dataloader: 
  # # type: DataLoader
  # dataset: 
  #   # type: VOCDetection
  #   # root: ./dataset/voc/
  #   # ann_file: trainval.txt
  #   # label_file: label_list.txt
  #   transforms:
  #     # type: Compose
  #     ops:
  #       - {type: RandomPhotometricDistort, p: 0.5}
  #       - {type: RandomZoomOut, fill: 0}
  #       - {type: RandomIoUCrop, p: 0.8}
  #       - {type: SanitizeBoundingBoxes, min_size: 1}
  #       - {type: RandomHorizontalFlip}
  #       - {type: Resize, size: [640, 640], }
  #       - {type: SanitizeBoundingBoxes, min_size: 1}
  #       - {type: ConvertPILImage, dtype: 'float32', scale: True}   
  #       - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
  #     policy:
  #       name: stop_epoch
  #       epoch: 71 # epoch in [71, ~) stop `ops`
  #       ops: ['RandomPhotometricDistort', 'RandomZoomOut', 'RandomIoUCrop']
  dataset_root : 'D:\\data\\__OTHERDATA__\\OD_Foundation_data\\train'
  mode : "train"
  num_imgs_per_folder : 10000
  shuffle: True
  total_batch_size: 16 # total batch size equals to 16 (4 * 4)
  num_workers: 4
  drop_last: True 
  # collate_fn:
  #   type: BatchImageCollateFuncion
  #   # scales: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800]
  #   scales: [320, 352, 384, 416, 480, 512, 512, 512, 544, 576, 608, 640, 672]
  #   # scales: [96, 128, 160, 192, 224, 256, 256, 256, 288, 320, 352, 384, 416]
  #   stop_epoch: 71 # epoch in [71, ~) stop `multiscales`




val_dataloader:
  # # type: DataLoader
  # dataset: 
  #   # type: VOCDetection
  #   # root: ./dataset/voc/
  #   # ann_file: test.txt
  #   # label_file: label_list.txt
  #   transforms:
  #     # type: Compose
  #     ops: 
  #       - {type: Resize, size: [640, 640]}
  #       - {type: ConvertPILImage, dtype: 'float32', scale: True}
  dataset_root : 'D:\\data\\__OTHERDATA__\\OD_Foundation_data\\val'
  mode : "val"
  num_imgs_per_folder : 1000
  shuffle: False
  total_batch_size: 16
  num_workers: 4
  drop_last: False
  # collate_fn:
  #   type: BatchImageCollateFuncion
    





sync_bn: True
find_unused_parameters: False


# use_amp: False
scaler:
  type: GradScaler
  enabled: True


# use_ema: False
# ema:
#   type: ModelEMA
#   decay: 0.9999
#   warmups: 2000




# voc detection params

task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 20
class_mapping_path : "D:\\data\\__OTHERDATA__\\OD_Foundation_data\\combined_class_mapping.yaml"
seed : 1234
# runtime params
print_freq: 100 #iterations
output_dir: '.\\ckpts'
plot_dir : '.\\ckpts\\plots'
log_dir : '.\\ckpts\\logs'
checkpoint_freq: 10 #epochs
plot_freq: 100 #iterations
resume_path : ~
start_epoch : 0
expt_name : 'trial'
tile_size : 256